---
title: "edhmanager"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load libraries:
```{r}
library(scryr)
library(plyr)
library(cowplot)
library(magick)
```

# Load deck:
```{r}
getCardInfo <- function(cardName) {
  rawInfo <- scryr::scry_card_name(cardName)
  if(!("toughness" %in% names(rawInfo))) {
    rawInfo$power <- "-"
    rawInfo$toughness <- "-"
  }
  if(!("flavor_text" %in% names(rawInfo))) {
    rawInfo$flavor_text <- "-"
  }
  if(!("oracle_text" %in% names(rawInfo))) {
    rawInfo$oracle_text <- "-"
  }
  if(length(rawInfo$prices[[1]]) == 0) {
    rawInfo$prices <- c(0)
  }
  rawInfo$usd <- as.numeric(rawInfo$prices[[1]][1])
  rawInfo$image <- as.character(rawInfo$image_uris[[1]][2])
  cardInfo <- rawInfo[,c("name", "colors", "color_identity", "cmc", "oracle_text", "power", "toughness", "type_line", "keywords", "flavor_text", "usd", "rarity", "image")]
  Sys.sleep(0.5)
  return(cardInfo)
}

LoadDeck <- function(csvPath) {
  deckRaw <- read.csv(file = csvPath, header = FALSE, sep = ";")
  deckList <- lapply(deckRaw$V1, getCardInfo)
  deckTbl <- do.call(rbind, deckList)
  deckDF <- as.data.frame(deckTbl)
  return(deckDF)
}

deck <- LoadDeck("decks/OMW.csv")
```

# Modify deck:
```{r}
addCard <- function(newCard, deckDF) {
  if(nrow(deckDF) < 100) {
    cardInfo <- NULL
    try(cardInfo <- getCardInfo(newCard))
    if(is.null(cardInfo)) {
      print("The card could not be found. No action was performed.")
      return(deckDF)
    }
    deckDF <- rbind(deckDF, cardInfo)
    print(paste0("Your deck is now ", as.character(100 - nrow(deckDF)), " cards from being full."))
    return(deckDF)
  } else {
    print("Your deck is already full, please remove cards before you add more.")
    return(deckDF)
  }
}

dropCard <- function(oldCard, deckDF) {
  oldCard <- tolower(oldCard)
  availableCards <- tolower(deckDF$name)
  if(oldCard %in% availableCards) {
    deckDF <- deckDF[-c(match(oldCard, availableCards)),]
    print(paste0("Your deck is now ", as.character(100 - nrow(deckDF)), " cards from being full."))
  } else {
    print("The card could not be found. No action was performed.")
  }
  return(deckDF)
}

deck <- addCard("forest", deck)
deck <- dropCard("forest", deck)
```

# Extract information:
```{r}
DeckStats <- function(deckDF) {
  cat("Commander deck stats\n####################\n")
  cat(paste0("Price: $", sum(deckDF$usd)), "\n\n")
  cat("Mana:\n*****\n")
  colorID <- unique(unlist(deckDF$color_identity, recursive = TRUE))
  colorID <- colorID[!(colorID == "NULL")]
  colorCheck <- function(x) {ifelse(x == "B", "black", ifelse(x == "G", "green", ifelse("R", "red", ifelse("U", "blue", ifelse("W", "white", "unknown")))))}
  colorID <- lapply(colorID, colorCheck)
  cat("- Color identity:", paste(colorID, collapse = ", "), "\n")
  cat("- Converted mana costs:")
  cmcs <- plyr::count(deckDF$cmc)
  print.data.frame(unname(cmcs[order(cmcs$x, decreasing = TRUE),]), row.names = FALSE)
  cat("\nCard types:\n***********")
  cardTypes <- gsub(" —.+|Legendary |Basic | // .+", "", deckDF$type_line)
  cardTypes <- plyr::count(unlist(cardTypes))
  print.data.frame(unname(cardTypes[order(cardTypes$freq, decreasing = TRUE),]), row.names = FALSE)
  cat("\nKeywords:\n*********")
  keywords <- plyr::count(unlist(deckDF$keywords))
  print.data.frame(unname(keywords[order(keywords$freq, decreasing = TRUE),]), row.names = FALSE)
}

DeckStats(deck)
```

# Interact with deck:
```{r fig.height=10, fig.width=15}
DrawHand <- function(deckDF) {
  urlVector <- sample(x = deck$image, size = 7, replace = FALSE)
  plotImage <- function(imageUrl) {
    plottedImage <- cowplot::ggdraw() +
    cowplot::draw_image(imageUrl)
    return(plottedImage)
  }
  allCards <- lapply(urlVector, plotImage)
  upperPlot <- cowplot::plot_grid(plotlist = allCards[1:4], nrow = 1)
  lowerPlot <- cowplot::plot_grid(plotlist = allCards[5:7], nrow = 1)
  cowplot::plot_grid(upperPlot, lowerPlot, nrow = 2) +
  theme(plot.background = element_rect(fill = "black"))
}

DrawHand(deck)
```

# Test cards against deck:
```{r}
# Function testing a card against the deck:
# - show which cards in the deck that interacts with the keywords of the card
# - show which cards (if any) that share a creature type with the card
```

# Write deck:
```{r}
writeDeck <- function(deckDF, csvPath) {
  write.table(x = as.vector(deckDF$name), file = csvPath, sep = ";", col.names = FALSE, row.names = FALSE, quote = FALSE)
}

writeDeck(deck, "decks/OMW.csv")
```
